//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStock.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSALE
    {
        public int SALESID { get; set; }
        public Nullable<int> PRODUCT { get; set; }
        public Nullable<int> CUSTOMER { get; set; }
        public Nullable<byte> PIECE { get; set; }
        public Nullable<decimal> PRİCE { get; set; }
    
        public virtual TBL_CUSTOMER TBL_CUSTOMER { get; set; }
        public virtual TBLPRODUCT TBLPRODUCT { get; set; }
    }
}
